@startuml GestionarUsuariosAdmin
class "AdminUsuariosView" as AdminView <<Boundary>> {
  + mostrarListaUsuarios()
  + opcionesCRUD()
}

class "AdminUsuarioController" as AdminController <<Controller>> {
  + listarUsuarios()
  + eliminarUsuario()
  + editarUsuario()
}

class "Usuario" as Usuario <<Entity>> {
  - id: int
  - activo: boolean
  + desactivar()
}

AdminView --> AdminController : "envía operación"
AdminController --> Usuario : "actualiza DB"
@enduml