@startuml AccederCatalogo
class "CatalogoView" as CatalogoView <<Boundary>> {
  + mostrarFrutas()
}

class "CatalogoController" as CatalogoController <<Controller>> {
  + obtenerFrutas()
}

class "Fruta" as Fruta <<Entity>> {
  - id: int
  - nombre: String
  - precio: float
}

CatalogoView --> CatalogoController : "solicita lista"
CatalogoController --> Fruta : "consulta DB"
@enduml