@startuml GestionarArticulosAdmin
class "AdminArticulosView" as AdminView <<CI>> {
  + mostrarOpcionesCRUD()
}

class "AdminArticuloController" as AdminController <<CC>> {
  + crearArticulo()
  + editarArticulo()
  + eliminarArticulo()
}

class "Articulo" as Articulo <<CE>> {
  - id: int
  - titulo: String
  + guardar()
  + eliminar()
}

AdminView --> AdminController : "envía operación"
AdminController --> Articulo : "actualiza DB"
@enduml